antibot: Exempt messages without a sender
Messages forwarded by Telegram from a channel linked to a group have no
sender field, so SenderGetter#get_sender() returns None.

Only group admins can link channels, so it's safe to assume that such
messages are safe.

Fixes the following error:
TypeError: Cannot cast NoneType to any kind of Peer.

Reported-by: Albert I <krascgq@outlook.co.id>
Suggested-by: Hackintosh 5 <hackintosh5@wildfyre.net>
Signed-off-by: Danny Lin <danny@kdrag0n.dev>