launch: Simplify asyncio event loop bootstrapping
This should also fix the following error on some Unix systems:

Traceback (most recent call last):
  File "pyrobud/core/command_dispatcher.py", line 133, in on_command
    ret = await cmd.func(ctx)
  File "pyrobud/modules/system.py", line 58, in cmd_sysinfo
    "neofetch", "--stdout", timeout=10
  File "pyrobud/util/system.py", line 59, in run_command
    proc = await _spawn_exec(cmdline, in_data, stdout, stderr, **kwargs)
  File "pyrobud/util/system.py", line 17, in _spawn_exec
    *cmdline, stdin=stdin, stdout=stdout, stderr=stderr, **kwargs
  File "/usr/lib/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1211, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 203, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 867, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached