context: respond: Discard old response when switching modes
Some commands, such as `s` and `sp`, will call ctx.respond() with the
default mode ("edit" in most cases) to provide an "Uploading" status
update, then call it again with the "repost" mode to send the actual
response -- usually to send a different type of message than the
invoking one.

This fixes the following error:
MessageNotModifiedError: Content of the message was not modified (caused by EditMessageRequest)

Fixes: bc08f8f ("Revamp command invocation system and add centralized argument validation")
Signed-off-by: Danny Lin <danny@kdrag0n.dev>