sticker: Fix Python 3.6 compatibility
The capture_output convenience argument was introduced in Python 3.7.

Fixes the following error:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

Signed-off-by: Danny Lin <danny@kdrag0n.dev>